#! python2
# -*- python -*-

# This software was produced by NIST, an agency of the U.S. government,
# and by statute is not subject to copyright in the United States.
# Recipients of this software assume all responsibilities associated
# with its operation, modification and maintenance. However, to
# facilitate maintenance we ask that before distributing modified
# versions of this software, you first contact the authors at
# oof_manager@ctcms.nist.gov. 

# This is the start-up script for oof2.  It is installed as an
# executable file in the bin directory, *not* the python library.
# "import oof2" statements refer to the oof2 module in the library,
# not to this file.

import sys
import os

# The base "oof" module must be in your path. You may need to
# set the PYTHONPATH environment variable on Linux or Mac OSX systems.
# If you are seeing failures on this line, your shell environment
# is a good place to start troubleshooting.
import oof2
sys.path.append(os.path.dirname(oof2.__file__))

# All user input is evaluated in this environment, so first import
# useful things like the math library.
from math import *

# The real start-up code is in ooflib.common.oof.  Until it is loaded,
# no modules containing oof C++ code can be used.  Therefore, don't
# even try loading any other oof code (not even the debug module)
# before here!

from ooflib.common import oof
oof.run()

sys.exit()
