OOF.Microstructure.Create_From_ImageFile(filename='../../TEST3D/ms_data/5color/slice*.tif', microstructure_name='slice*.tif', height=automatic, width=automatic, depth=automatic)
OOF.Image.AutoGroup(image='slice*.tif:slice*.tif')
OOF.Windows.Graphics.New()
OOF.PixelGroup.Rename(microstructure='slice*.tif', group='RGBColor(red=0.95294117647058818,green=0.34901960784313724,blue=0.34901960784313724)', new_name='redvoxels')
OOF.PixelGroup.Rename(microstructure='slice*.tif', group='RGBColor(red=0.95294117647058818,green=0.95294117647058818,blue=0.34901960784313724)', new_name='yellowvoxels')
OOF.PixelGroup.Rename(microstructure='slice*.tif', group='RGBColor(red=0.99607843137254903,green=0.99607843137254903,blue=0.99607843137254903)', new_name='whitevoxels')
OOF.PixelGroup.Rename(microstructure='slice*.tif', group='RGBColor(red=0.34901960784313724,green=0.95294117647058818,blue=0.34901960784313724)', new_name='greenvoxels')
OOF.PixelGroup.Rename(microstructure='slice*.tif', group='RGBColor(red=0.34901960784313724,green=0.34901960784313724,blue=0.95294117647058818)', new_name='bluevoxels')
OOF.Property.Copy(property='Color', new_name='redcolor')
OOF.Property.Parametrize.Color.redcolor(color=RGBColor(red=1,green=0,blue=0))
OOF.Property.Copy(property='Color', new_name='bluecolor')
OOF.Property.Parametrize.Color.bluecolor(color=RGBColor(red=0,green=0,blue=1))
OOF.Property.Copy(property='Color:bluecolor', new_name='yellowcolor')
OOF.Property.Parametrize.Color.yellowcolor(color=RGBColor(red=1,green=1,blue=0))
OOF.Property.Copy(property='Color:yellowcolor', new_name='greencolor')
OOF.Property.Parametrize.Color.greencolor(color=RGBColor(red=0,green=1,blue=0))
OOF.Property.Copy(property='Color:greencolor', new_name='whitecolor')
OOF.Property.Parametrize.Color.whitecolor(color=Gray(value=0.65079365079365081))
OOF.Material.New(name='red', material_type='bulk')
OOF.Material.Assign(material='red', microstructure='slice*.tif', pixels='redvoxels')
OOF.Material.New(name='blue', material_type='bulk')
OOF.Material.Assign(material='blue', microstructure='slice*.tif', pixels='bluevoxels')
OOF.Material.New(name='yellow', material_type='bulk')
OOF.Material.Assign(material='yellow', microstructure='slice*.tif', pixels='yellowvoxels')
OOF.Material.New(name='green', material_type='bulk')
OOF.Material.Assign(material='green', microstructure='slice*.tif', pixels='greenvoxels')
OOF.Material.New(name='white', material_type='bulk')
OOF.Material.Assign(material='white', microstructure='slice*.tif', pixels='whitevoxels')
OOF.Material.Add_property(name='red', property='Color:redcolor')
OOF.Material.Add_property(name='yellow', property='Color:yellowcolor')
OOF.Material.Add_property(name='green', property='Color:greencolor')
OOF.Material.Add_property(name='blue', property='Color:bluecolor')
OOF.Material.Add_property(name='white', property='Color:whitecolor')
OOF.Graphics_1.Settings.Color.Background(color=Gray(value=0.55555555555555558))
OOF.Skeleton.New(name='skeleton', microstructure='slice*.tif', x_elements=4, y_elements=4, z_elements=4, skeleton_geometry=BrickSkeleton(left_right_periodicity=False,top_bottom_periodicity=False,front_back_periodicity=False))
OOF.Graphics_1.Settings.List_All_Layers(1)
OOF.Graphics_1.Layer.Select(n=3)
OOF.LayerEditor.LayerSet.Edit(window='Graphics_1', layer_number=3)
OOF.LayerEditor.LayerSet.Replace_Method(layer_number=0, method=SkeletonEdgeDisplay(color=Gray(value=0.0),width=3))
OOF.LayerEditor.LayerSet.Send(window='Graphics_1')
OOF.Graphics_1.Toolbox.Pixel_Info.Query(x=0, y=0, z=19)
OOF.Graphics_1.Toolbox.Pixel_Info.Query(x=1, y=1, z=19)
